### ISSUE TITLE
Obtención de votaciones cifradas (Mejora de trabajos)

### ISSUE THREAD

**Issue by Lammerlord92** [AgoraUS1516/G02#1]
Buenas, en caso de que consigamos desplegar en recuento, nos gustaría saber como conseguir los datos cifrados de una votación. Cuando podáis, enviadnos lo necesario para sacar dicha información (URL y demás)

**Comment by manrevlob** [comment]
Buenas, en nuestra web disponéis de toda la información detallada de nuestra API:
http://egcphp-alm1516.rhcloud.com/ 

Para vuestro caso, recoger los votos de una votación sería:
https://egcphp-alm1516.rhcloud.com/API/get_votes.php?votation_id=X ,siendo X el ID de la votación. Los votos se devuelven en texto plano y aparecen sin cifrar debidos a que están sin cifrar en la BBDD ya que son de prueba.

Si tenéis mas dudas no dudéis en preguntarnos.

**Comment by Lammerlord92** [comment]
perfecto, cierro incidencia
